### ISSUE TITLE
Use pytest or unitest for testing

### ISSUE THREAD

**Issue by thedataking** [immunant/dwarf-writer#1]
Might as well reuse what's already there.

**Comment by ayrtonm** [comment]
I removed the test runner script and rewrote the test cases to use pytest and it works locally. I also tried switching to pytest by changing the last line in ci.yml in the github-actions branch but it can't seem to find pytest so I'll just run tests locally in the meantime.

**Comment by thedataking** [comment]
@ayrtonm Did you try installing `pytest` with `pip install -U pytest` (or `pip3 install -U pytest`) in ci.yml?
